services:
    postgres:
        env_file:
            - .env.production
    backend:
        restart: always
        env_file:
            - .env.production
        volumes:
            - python-dependencies:/app/.venv
        command:
            - uvicorn
            - app.main:app
            - --host
            - 0.0.0.0
            - --port
            - '8000'
    frontend:
        restart: always
        env_file:
            - .env.production
        volumes:
            - node-modules:/app/node_modules
        command:
            - pnpm
            - start
